import type { CategoryDef, ItemDef } from "./schema";

export const CATEGORIES: CategoryDef[] = [
  { id: "infrastructure", name: "Infrastructure", emoji: "🏗️" },
  { id: "zones", name: "Zones", emoji: "🏘️" },
  { id: "transit", name: "Transit", emoji: "🚌" },
  { id: "eduhealth", name: "Edu & Health", emoji: "🏥" },
  { id: "culture", name: "Culture & Parks", emoji: "🌳" },
  { id: "services", name: "Services", emoji: "🚒" },
];

export const ITEMS: ItemDef[] = [
  // ── Infrastructure ────────────────────────────────────────────────
  {
    id: "road",
    name: "Road",
    category: "infrastructure",
    kind: "road",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: false,
    art: { base: 0x9aa0ab, accent: 0xf5f0e6, shape: "roundedRect" },
    effects: {},
  },
  {
    id: "train-line",
    name: "Train Line",
    category: "infrastructure",
    kind: "rail",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: false,
    art: { base: 0xe8743b, shape: "roundedRect" },
    effects: {},
  },
  {
    id: "subway-line",
    name: "Subway Line",
    category: "infrastructure",
    kind: "subway",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: false,
    art: { base: 0x7b5bd1, shape: "roundedRect" },
    effects: {},
  },

  // ── Zones (painted) ───────────────────────────────────────────────
  {
    id: "zone-residential",
    name: "Residential",
    category: "zones",
    kind: "zone",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: false,
    art: { base: 0x8fd14f, shape: "roundedRect" },
    effects: { populationPerTile: 8 },
  },
  {
    id: "zone-commercial",
    name: "Commercial",
    category: "zones",
    kind: "zone",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: false,
    art: { base: 0x5fb8e8, shape: "roundedRect" },
    effects: { jobsPerTile: 6 },
  },
  {
    id: "zone-industrial",
    name: "Industrial",
    category: "zones",
    kind: "zone",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: false,
    art: { base: 0xe8b75f, shape: "roundedRect" },
    effects: { jobsPerTile: 10, happiness: { radius: 3, delta: -2 } },
  },

  // ── Transit ───────────────────────────────────────────────────────
  {
    id: "bus-stop",
    name: "Bus Stop",
    category: "transit",
    kind: "building",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0xffd24d, accent: 0x4d6b8c, icon: "bus", shape: "roundedRect" },
    effects: { coverage: { layer: "transit", radius: 6 } },
  },
  {
    id: "subway-station",
    name: "Subway Station",
    category: "transit",
    kind: "building",
    footprint: { w: 2, h: 2 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0x7b5bd1, accent: 0x4a3585, icon: "subway", shape: "roundedRect" },
    effects: { coverage: { layer: "transit", radius: 6 } },
  },
  {
    id: "train-station",
    name: "Train Station",
    category: "transit",
    kind: "building",
    footprint: { w: 3, h: 2 },
    rotatable: true,
    requiresRoadAdjacency: true,
    art: { base: 0xf2a65a, accent: 0x6b4f3a, icon: "train", shape: "roundedRect" },
    effects: { coverage: { layer: "transit", radius: 12 } },
  },

  // ── Education & Health ────────────────────────────────────────────
  {
    id: "school",
    name: "School",
    category: "eduhealth",
    kind: "building",
    footprint: { w: 2, h: 2 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0xf8c64b, accent: 0xc94f4f, icon: "book", shape: "roundedRect" },
    effects: { coverage: { layer: "education", radius: 9 } },
  },
  {
    id: "university",
    name: "University",
    category: "eduhealth",
    kind: "building",
    footprint: { w: 3, h: 3 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0xb98ae0, accent: 0x6e4a9e, icon: "grad-cap", shape: "roundedRect" },
    effects: { coverage: { layer: "education", radius: 16 } },
  },
  {
    id: "clinic",
    name: "Clinic",
    category: "eduhealth",
    kind: "building",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0xf2f2f2, accent: 0xe05c5c, icon: "cross", shape: "roundedRect" },
    effects: { coverage: { layer: "health", radius: 6 } },
  },
  {
    id: "hospital",
    name: "Hospital",
    category: "eduhealth",
    kind: "building",
    footprint: { w: 3, h: 3 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0xfafafa, accent: 0xe05c5c, icon: "cross", shape: "roundedRect" },
    effects: { coverage: { layer: "health", radius: 14 } },
  },

  // ── Culture & Parks ───────────────────────────────────────────────
  {
    id: "park",
    name: "Park",
    category: "culture",
    kind: "building",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: false,
    art: { base: 0x6fbf5a, accent: 0x3e8a3e, icon: "tree", shape: "roundedRect" },
    effects: { happiness: { radius: 4, delta: 2 } },
  },
  {
    id: "big-park",
    name: "Big Park",
    category: "culture",
    kind: "building",
    footprint: { w: 2, h: 2 },
    rotatable: false,
    requiresRoadAdjacency: false,
    art: { base: 0x5fb350, accent: 0x2f7a3a, icon: "tree", shape: "roundedRect" },
    effects: { happiness: { radius: 6, delta: 3 } },
  },
  {
    id: "plaza",
    name: "Plaza",
    category: "culture",
    kind: "building",
    footprint: { w: 1, h: 1 },
    rotatable: false,
    requiresRoadAdjacency: false,
    art: { base: 0xd9c8a9, accent: 0x5fa8d3, icon: "fountain", shape: "roundedRect" },
    effects: { happiness: { radius: 3, delta: 1 } },
  },
  {
    id: "museum",
    name: "Museum",
    category: "culture",
    kind: "building",
    footprint: { w: 2, h: 2 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0xd8d3c8, accent: 0x8a7f6a, icon: "column", shape: "roundedRect" },
    effects: { happiness: { radius: 8, delta: 2 } },
  },
  {
    id: "stadium",
    name: "Stadium",
    category: "culture",
    kind: "building",
    footprint: { w: 4, h: 4 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0x7fd4c0, accent: 0x3a8a78, icon: "ball", shape: "roundedRect" },
    effects: { happiness: { radius: 10, delta: 2 } },
  },

  // ── Services ──────────────────────────────────────────────────────
  {
    id: "police",
    name: "Police Station",
    category: "services",
    kind: "building",
    footprint: { w: 2, h: 2 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0x7d9fd1, accent: 0x2f4a7a, icon: "shield", shape: "roundedRect" },
    effects: { coverage: { layer: "safety", radius: 10 } },
  },
  {
    id: "fire-station",
    name: "Fire Station",
    category: "services",
    kind: "building",
    footprint: { w: 2, h: 2 },
    rotatable: false,
    requiresRoadAdjacency: true,
    art: { base: 0xe07a5f, accent: 0xa33b2e, icon: "flame", shape: "roundedRect" },
    effects: { coverage: { layer: "safety", radius: 10 } },
  },
];

const itemsById = new Map(ITEMS.map((item) => [item.id, item]));

export function getItem(id: string): ItemDef | undefined {
  return itemsById.get(id);
}

export function itemsInCategory(category: string): ItemDef[] {
  return ITEMS.filter((item) => item.category === category);
}
